[workspace]
members = [
    "crates/common",
    "crates/compiler",
    "crates/ethereum",
    "crates/executor",
    "crates/gateway-client",
    "crates/gateway-test-fixtures",
    "crates/gateway-types",
    "crates/merkle-tree",
    "crates/p2p",
    "crates/p2p_bootstrap",
    "crates/p2p_proto",
    "crates/p2p_proto_derive",
    "crates/p2p_proto_v0",
    "crates/pathfinder",
    "crates/retry",
    "crates/rpc",
    "crates/serde",
    "crates/stark_curve",
    "crates/stark_hash",
    "crates/stark_poseidon",
    "crates/storage",
]
exclude = [
    "crates/load-test",
    "crates/stark_hash_python",
    "utils/pathfinder-probe",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.75"
assert_matches = "1.5.0"
base64 = "0.13.1"
bitvec = "1.0.1"
blockifier = { git = "https://github.com/starkware-libs/blockifier", rev = "ebf48c445b965c5c55b8c724338be7c6e21ffdd4" }
clap = "4.1.13"
const_format = "0.2.31"
criterion = "0.5.1"
fake = { version = "2.8.0", features = ["derive"] }
lazy_static = "1.4.0"
primitive-types = "0.12.1"
pretty_assertions = "1.4.0"
rand = "0.8.5"
semver = "1.0.18"
serde = "=1.0.188"
serde_json = "1.0.105"
serde_with = "3.0.0"
# This one needs to match the version used by blockifier
starknet_api = "0.4.1"
thiserror = "1.0.48"
tokio = "1.29.1"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
zstd = "0.12.4"
