[package]
name = "pathfinder-serde"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
num-bigint = { workspace = true }
pathfinder-common = { path = "../common" }
primitive-types = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true }
stark_hash = { path = "../stark_hash" }

[dev-dependencies]
pretty_assertions = { workspace = true }
