[package]
name = "pathfinder-merkle-tree"
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
bitvec = { workspace = true }
pathfinder-common = { path = "../common" }
pathfinder-storage = { path = "../storage" }
rand = { workspace = true }
stark_curve = { path = "../stark_curve" }
stark_hash = { path = "../stark_hash" }
stark_poseidon = { path = "../stark_poseidon" }
starknet-gateway-types = { path = "../gateway-types" }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
