[package]
name = "pathfinder-ethereum"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.62"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
const-decoder = "0.3.0"
hex = "0.4.3"
keccak-hash = "0.10.0"
pathfinder-common = { path = "../common" }
primitive-types = { workspace = true }
reqwest = { version = "0.11.18", features = ["json"] }
serde_json = { workspace = true }
stark_hash = { path = "../stark_hash" }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
hex = "0.4.3"
httpmock = "0.6.8"
tokio = { workspace = true, features = ["macros"] }
