[package]
name = "pathfinder-common"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
full-serde = []

[dependencies]
anyhow = { workspace = true }
bitvec = { workspace = true }
fake = { workspace = true }
metrics = { workspace = true }
num-bigint = { workspace = true }
paste = "1.0.14"
primitive-types = { workspace = true, features = ["serde"] }
rand = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = [
    "arbitrary_precision",
    "raw_value",
] }
serde_with = { workspace = true }
sha3 = "0.10"
stark_curve = { path = "../stark_curve" }
stark_hash = { path = "../stark_hash" }
stark_poseidon = { path = "../stark_poseidon" }
thiserror = { workspace = true }

[build-dependencies]
vergen = { version = "8", default-features = false, features = [
    "git",
    "gitcl",
] }
