[package]
name = "p2p_stream"
description = "Extension of libp2p-request-response that allows for streaming responses to a single request."
authors = ["Parity Technologies <admin@parity.io>", "Equilibrium Labs <info@equilibrium.co>"]
version = "0.1.0"
edition = { workspace = true }
license = { workspace = true }
rust-version = { workspace = true }

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
futures-bounded = "0.2.1"
futures-timer = "3.0.2"
libp2p = { version = "0.53.0", default-features = false, features = [
    "identify",
    "noise",
    "tcp",
    "tokio",
] }
rand = { workspace = true }
serde = { version = "1.0", optional = true }
smallvec = "1.11.1"
tracing = { workspace = true }
void = "1.0.2"

[dev-dependencies]
anyhow = { workspace = true }
futures_ringbuf = "0.4.0"
rand = { workspace = true }
serde = { workspace = true }
tracing-subscriber = { workspace = true }
