[package]
name = "p2p"
version = "0.1.0"
edition = "2021"
description = "Pathfinder P2P"
license = "MIT OR Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
futures = { workspace = true }
libp2p = { version = "0.51.3", default-features = false, features = [
    "autonat",
    "dcutr",
    "dns",
    "gossipsub",
    "identify",
    "kad",
    "macros",
    "noise",
    "ping",
    "relay",
    "request-response",
    "tcp",
    "tokio",
    "yamux",
] }
p2p_proto_v0 = { path = "../p2p_proto_v0" }
pathfinder-common = { path = "../common" }
prost = "0.12.1"
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = "0.10.7"
stark_hash = { path = "../stark_hash" }
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread", "sync"] }
tracing = "0.1.37"
void = "1.0.2"
zeroize = "1.6.0"

[dev-dependencies]
assert_matches = { workspace = true }
clap = { workspace = true, features = ["derive", "env", "wrap_help"] }
env_logger = "0.10.0"
fake = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
test-log = { version = "0.2.12", default-features = false, features = [
    "trace",
] }
tokio = { version = "1.32.0", features = ["test-util"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
